services:
  qarea.extjshelper.twig.extension:
    class: QArea\ExtJSHelperBundle\Twig\Extensions\ExtJSExtension
    arguments:
      - %qarea.extjshelper.twig.extension.extjs_root%
      - %qarea.extjshelper.twig.extension.type%
      - %qarea.extjshelper.twig.extension.theme%
    tags:
      - { name: twig.extension }